"use client";
// import { ThirdwebProvider } from "@thirdweb-dev/react";
import {Provider} from "react-redux"
import {store} from "../app/redux/store"
import {WalletProvider} from "./contextApiWallet"
import { loadStripe } from '@stripe/stripe-js';
const stripePromise = loadStripe('your-public-key-here');
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <html className="bg-white
    " lang="en">
     <body>
      <WalletProvider >
        
       <Provider  store={store}  > {children}</Provider>
       </WalletProvider>
       </body>
    </html>
  )
}
